name: repack_resigner_apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  repack-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Java runtime
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Show Java version
        run: java --version

      - name: Repack source code to unsigned APK
        run: java -jar tools/apktool_2.9.1.jar b source_code -o source_code/dist/llrj_QL_unsigned_${GITHUB_SHA}.apk

      - name: Resign the new APK package
        run: java -jar tools/uber-apk-signer-1.3.0.jar --apk source_code/dist/llrj_QL_unsigned_${GITHUB_SHA}.apk -o source_code/dist/

      - name: Rename APK
        run: mv source_code/dist/llrj_QL_unsigned${GITHUB_SHA}-aligned-debugSigned.apk source_code/dist/llrj_QL_signed.apk 

      - name: Rename idsig
        run: mv source_code/dist/llrj_QL_unsigned${GITHUB_SHA}-aligned-debugSigned.apk.idsig source_code/dist/llrj_QL_signed${GITHUB_SHA}.apk.idsig
