name: repack_resigner_apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  repack-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Java runtime
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Show Java version
        run: java --version

      - name: create target output directory
        run: mkdir -p source/dist

      - name: Repack source code to unsigned APK
        run: java -jar tools/apktool_2.9.1.jar b source_code -o source_code/dist/llrj_QL_unsigned_${GITHUB_SHA}.apk

      - name: Resign the new APK package
        run: java -jar tools/uber-apk-signer-1.3.0.jar --apk source_code/dist/llrj_QL_unsigned_${GITHUB_SHA}.apk -o source_code/dist/

      - name: Rename APK
        run: mv source_code/dist/llrj_QL_unsigned_${GITHUB_SHA}-aligned-debugSigned.apk source_code/dist/llrj_QL_signed_${GITHUB_SHA}.apk 

      - name: Rename idsig
        run: mv source_code/dist/llrj_QL_unsigned_${GITHUB_SHA}-aligned-debugSigned.apk.idsig source_code/dist/llrj_QL_signed_${GITHUB_SHA}.apk.idsig

      - name: Upload APK to artifact
        uses: actions/upload-artifact@v2
        with:
          name: llrj_QL_signed
          path: source_code/dist/

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: source_code/dist/llrj_QL_signed_${GITHUB_SHA}.apk
          asset_name: llrj_QL_signed_${GITHUB_SHA}.apk
          asset_content_type: application/vnd.android.package-archive
        # token: ${{ secrets.ACTION_TOKEN }}